spring:
   application:
      name: service-auth
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/oauth2_study?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: '088114'
   redis:
      host: localhost
      port: 6379
      password: 
      database: 0
      
server:
   port: 9098
eureka:
   client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
         defaultZone: http://localhost:8761/eureka/

mybatis:
   mapper-locations: classpath:mapper/*.xml